# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: BuildAndTest
    displayName: Build and test
    jobs:
      - job: BuildImage
        displayName: Build docker image
        steps:
          - bash: echo starting to build superman docker image majidshaikh16/superman:$(Build.BuildId)
          - task: Docker@2
            displayName: Building an image to docker hub
            inputs:
              containerRegistry: 'majidshaikh16/dockerhub'
              repository: 'majidshaikh16/superman'
              command: 'build'
              Dockerfile: '$(Build.SourcesDirectory)/front-end/superman/Dockerfile'
              tags: $(Build.BuildId)
          - bash: echo image build successful majidshaikh16/superman:$(Build.BuildId)
  - stage: PushImage
    displayName: Pushing the image to docker hub
    dependsOn: BuildAndTest
    jobs:
      - job: PushImage
        displayName: Push docker image
        steps:
          - bash: echo starting to push the docker image majidshaikh16/superman:$(Build.BuildId)
          - task: Docker@2
            inputs:
              containerRegistry: 'majidshaikh16/dockerhub'
              repository: 'majidshaikh16/superman'
              command: 'push'
              tags: $(Build.BuildId)
          - bash: echo pushed the docker image majidshaikh16/superman:$(Build.BuildId)

# stages:
# - stage: Build
#   displayName: Build image
#   jobs:  
#   - job: Build
#     displayName: Build
#     pool:
#       vmImage: 'ubuntu-latest'
#     steps:
#     - task: Docker@2
#       displayName: Build and push an image to docker hub
#       inputs:
#          containerRegistry: 'majidshaikh16/dockerhub'
#          repository: 'majidshaikh16/superman'
#          command: 'buildAndPush'
#          Dockerfile: '$(Build.SourcesDirectory)/front-end/superman/Dockerfile'
#          tags: '$(tag)'