# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push an image to docker hub
      inputs:
         containerRegistry: 'majidshaikh16/dockerhub'
         repository: 'majidshaikh16/superman'
         command: 'buildAndPush'
         Dockerfile: '$(Build.SourcesDirectory)/front-end/superman/Dockerfile'
         tags: '$(tag)'