# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: BuildAndPushImage
    displayName: Build and push
    jobs:
      - job: BuildAndPushImage
        displayName: Build docker image
        steps:
          - bash: echo starting to build superman docker image majidshaikh16/superman:$(tag)
          - task: Docker@2
            displayName: Building an image to docker hub
            inputs:
              containerRegistry: 'majidshaikh16/dockerhub'
              repository: 'majidshaikh16/superman'
              command: 'buildAndPush'
              Dockerfile: '$(Build.SourcesDirectory)/front-end/superman/Dockerfile'
              tags: '$(tag)'
          - bash: echo image build successful majidshaikh16/superman:$(tag) and pushed to $(containerRegistry)
  - stage: UAT
    displayName: Some task to perform on UAT
    dependsOn: BuildAndPushImage
    jobs:
      - job: UpdateUat
        displayName: Deploy to uat
        steps:
          - bash: echo starting to update uat with the docker image majidshaikh16/superman:$(tag)
          - bash: echo success updated docker image majidshaikh16/superman:$(tag)
  - stage: PPR
    displayName: Some task to perform on PPR
    dependsOn: BuildAndPushImage
    jobs:
      - job: UpdatePPR
        displayName: Deploy to PPR
        steps:
          - bash: echo starting to update PPR with the docker image majidshaikh16/superman:$(tag)
          - bash: echo success updated docker image majidshaikh16/superman:$(tag)
  - stage: CleanUp
    displayName: Independent cleanup task
    jobs:
      - job: CleanUp
        displayName: Independent clean up
        steps:
          - bash: echo starting the clean up...
          - bash: clean up completed...                

# stages:
# - stage: Build
#   displayName: Build image
#   jobs:  
#   - job: Build
#     displayName: Build
#     pool:
#       vmImage: 'ubuntu-latest'
#     steps:
#     - task: Docker@2
#       displayName: Build and push an image to docker hub
#       inputs:
#          containerRegistry: 'majidshaikh16/dockerhub'
#          repository: 'majidshaikh16/superman'
#          command: 'buildAndPush'
#          Dockerfile: '$(Build.SourcesDirectory)/front-end/superman/Dockerfile'
#          tags: '$(tag)'